;;; WARNING: This is a generated file, editing it is not advised!
(in-package :cl-user)
(asdf:operate 'asdf:load-op :verrazano-runtime)
(DEFPACKAGE :POSIX-CFFI-BINDINGS (:USE :CFFI) (:NICKNAMES :POSIX)
            (:EXPORT "+AT-EACCESS+" "+AT-SYMLINK-FOLLOW+" "+AT-REMOVEDIR+" "+AT-SYMLINK-NOFOLLOW+"
             "+AT-FDCWD+" "+SEEK-END-1+" "+SEEK-CUR-1+" "+SEEK-SET-1+" "+SPLICE-F-GIFT+"
             "+SPLICE-F-MORE+" "+SPLICE-F-NONBLOCK+" "+SPLICE-F-MOVE+"
             "+SYNC-FILE-RANGE-WAIT-AFTER+" "+SYNC-FILE-RANGE-WRITE+"
             "+SYNC-FILE-RANGE-WAIT-BEFORE+" "+POSIX-FADV-NOREUSE+" "+POSIX-FADV-DONTNEED+"
             "+POSIX-FADV-WILLNEED+" "+POSIX-FADV-SEQUENTIAL+" "+POSIX-FADV-RANDOM+"
             "+POSIX-FADV-NORMAL+" "+DN-MULTISHOT+" "+DN-ATTRIB+" "+DN-RENAME+" "+DN-DELETE+"
             "+DN-CREATE+" "+DN-MODIFY+" "+DN-ACCESS+" "+LOCK-RW+" "+LOCK-WRITE+" "+LOCK-READ+"
             "+LOCK-MAND+" "+LOCK-UN+" "+LOCK-NB+" "+LOCK-EX+" "+LOCK-SH+" "+F-SHLCK+" "+F-EXLCK+"
             "+F-UNLCK+" "+F-WRLCK+" "+F-RDLCK+" "+FD-CLOEXEC+" "+F-NOTIFY+" "+F-GETLEASE+"
             "+F-SETLEASE+" "+F-GETSIG+" "+F-SETSIG+" "+F-GETOWN+" "+F-SETOWN+" "+F-SETLKW-64+"
             "+F-SETLK-64+" "+F-GETLK-64+" "+F-SETLKW+" "+F-SETLK+" "+F-GETLK+" "+F-SETFL+"
             "+F-GETFL+" "+F-SETFD+" "+F-GETFD+" "+F-DUPFD+" "+O-LARGEFILE+" "+O-NOATIME+"
             "+O-NOFOLLOW+" "+O-DIRECTORY+" "+O-DIRECT+" "+O-ASYNC+" "+O-SYNC+" "+O-NONBLOCK+"
             "+O-APPEND+" "+O-TRUNC+" "+O-NOCTTY+" "+O-EXCL+" "+O-CREAT+" "+O-RDWR+" "+O-WRONLY+"
             "+O-RDONLY+" "+O-ACCMODE+" "+_FCNTL-H+" "+F-TEST+" "+F-TLOCK+" "+F-LOCK+" "+F-ULOCK+"
             "+SEEK-END+" "+SEEK-CUR+" "+SEEK-SET+" "+F-OK+" "+X-OK+" "+W-OK+" "+R-OK+"
             "+STDERR-FILENO+" "+STDOUT-FILENO+" "+STDIN-FILENO+" "+_XOPEN-LEGACY+"
             "+_XOPEN-ENH-I-18-N+" "+_XOPEN-CRYPT+" "+_XOPEN-UNIX+" "+_XOPEN-XPG-4+"
             "+_XOPEN-XPG-3+" "+_XOPEN-XPG-2+" "+_XOPEN-XCU-VERSION+" "+_XOPEN-VERSION+"
             "+_UNISTD-H+" "ACCESS" "EUIDACCESS" "EACCESS" "FACCESSAT" "LSEEK" "LSEEK-64" "CLOSE"
             "READ" "WRITE" "PREAD" "PWRITE" "PREAD-64" "PWRITE-64" "PIPE" "ALARM" "SLEEP" "UALARM"
             "USLEEP" "PAUSE" "CHOWN" "FCHOWN" "LCHOWN" "FCHOWNAT" "CHDIR" "FCHDIR" "GETCWD"
             "GET-CURRENT-DIR-NAME" "GETWD" "DUP" "DUP-2" "EXECVE" "FEXECVE" "EXECV" "EXECLE"
             "EXECL" "EXECVP" "EXECLP" "NICE" "PATHCONF" "FPATHCONF" "SYSCONF" "CONFSTR" "GETPID"
             "GETPPID" "GETPGRP" "GETPGID" "SETPGID" "SETPGRP" "SETSID" "GETSID" "GETUID" "GETEUID"
             "GETGID" "GETEGID" "GETGROUPS" "GROUP-MEMBER" "SETUID" "SETREUID" "SETEUID" "SETGID"
             "SETREGID" "SETEGID" "GETRESUID" "GETRESGID" "SETRESUID" "SETRESGID" "FORK" "VFORK"
             "TTYNAME" "TTYNAME-R" "ISATTY" "TTYSLOT" "LINK" "LINKAT" "SYMLINK" "READLINK"
             "SYMLINKAT" "READLINKAT" "UNLINK" "UNLINKAT" "RMDIR" "TCGETPGRP" "TCSETPGRP"
             "GETLOGIN" "GETLOGIN-R" "SETLOGIN" "GETHOSTNAME" "SETHOSTNAME" "SETHOSTID"
             "GETDOMAINNAME" "SETDOMAINNAME" "VHANGUP" "REVOKE" "PROFIL" "ACCT" "GETUSERSHELL"
             "ENDUSERSHELL" "SETUSERSHELL" "DAEMON" "CHROOT" "GETPASS" "FSYNC" "GETHOSTID" "SYNC"
             "GETPAGESIZE" "GETDTABLESIZE" "TRUNCATE" "TRUNCATE-64" "FTRUNCATE" "FTRUNCATE-64"
             "BRK" "SBRK" "SYSCALL" "LOCKF" "LOCKF-64" "FDATASYNC" "CRYPT" "ENCRYPT" "SWAB"
             "CTERMID" "READAHEAD" "SYNC-FILE-RANGE" "VMSPLICE" "SPLICE" "TEE" "FCNTL" "OPEN"
             "OPEN-64" "OPENAT" "OPENAT-64" "CREAT" "CREAT-64" "POSIX-FADVISE" "POSIX-FADVISE-64"
             "POSIX-FALLOCATE" "POSIX-FALLOCATE-64" "FLOCK-64" "FLOCK" "IOVEC" "GID-T" "UID-T"
             "OFF-T" "OFF-64-T" "USECONDS-T" "PID-T" "SOCKLEN-T" "INTPTR-T" "SSIZE-T" "SIZE-T"))

(in-package :POSIX-CFFI-BINDINGS)
(cffi::defctype* size-t :unsigned-int)
(cffi:defcstruct iovec (iov-base :pointer) (iov-len size-t))
(cffi::defctype* _-off-t :long)
(cffi::defctype* _-pid-t :int)
(cffi:defcstruct flock (l-type :short) (l-whence :short) (l-start _-off-t) (l-len _-off-t)
 (l-pid _-pid-t))
(cffi::defctype* _-off-64-t _-quad-t)
(cffi::defctype* _-quad-t :long-long)
(cffi:defcstruct flock-64 (l-type :short) (l-whence :short) (l-start _-off-64-t) (l-len _-off-64-t)
 (l-pid _-pid-t))
(cffi::defctype* _-mode-t :unsigned-int)
(cffi::defctype* ssize-t _-ssize-t)
(cffi::defctype* _-ssize-t :int)
(cffi::defctype* intptr-t _-intptr-t)
(cffi::defctype* _-intptr-t :int)
(cffi::defctype* _-gid-t :unsigned-int)
(cffi::defctype* _-uid-t :unsigned-int)
(cffi::defctype* _-useconds-t :unsigned-int)
(cffi::defctype* socklen-t _-socklen-t)
(cffi::defctype* _-socklen-t :unsigned-int)
(cffi::defctype* pid-t _-pid-t)
(cffi::defctype* useconds-t _-useconds-t)
(cffi::defctype* off-64-t _-off-64-t)
(cffi::defctype* off-t _-off-t)
(cffi::defctype* uid-t _-uid-t)
(cffi::defctype* gid-t _-gid-t)
(cl:progn
 (cffi:defcfun ("posix_fallocate64" posix-fallocate-64) :int (__fd :int) (__offset _-off-64-t)
  (__len _-off-64-t))
 (cffi:defcfun ("posix_fallocate" posix-fallocate) :int (__fd :int) (__offset _-off-t)
  (__len _-off-t))
 (cffi:defcfun ("posix_fadvise64" posix-fadvise-64) :int (__fd :int) (__offset _-off-64-t)
  (__len _-off-64-t) (__advise :int))
 (cffi:defcfun ("posix_fadvise" posix-fadvise) :int (__fd :int) (__offset _-off-t) (__len _-off-t)
  (__advise :int))
 (cffi:defcfun ("creat64" creat-64) :int (__file :string) (__mode _-mode-t))
 (cffi:defcfun ("creat" creat) :int (__file :string) (__mode _-mode-t))
 (cffi:defcfun ("openat64" openat-64) :int (__fd :int) (__file :string) (__oflag :int))
 (cffi:defcfun ("openat" openat) :int (__fd :int) (__file :string) (__oflag :int))
 (cffi:defcfun ("open64" open-64) :int (__file :string) (__oflag :int))
 (cffi:defcfun ("open" open) :int (__file :string) (__oflag :int))
 (cffi:defcfun ("fcntl" fcntl) :int (__fd :int) (__cmd :int))
 (cffi:defcfun ("tee" tee) :int (__fdin :int) (__fdout :int) (__len size-t)
  (__flags :unsigned-int))
 (cffi:defcfun ("splice" splice) :int (__fdin :int) (__offin :pointer) (__fdout :int)
  (__offout :pointer) (__len size-t) (__flags :unsigned-int))
 (cffi:defcfun ("vmsplice" vmsplice) :int (__fdout :int) (__iov :pointer) (__count size-t)
  (__flags :unsigned-int))
 (cffi:defcfun ("sync_file_range" sync-file-range) :int (__fd :int) (__from _-off-64-t)
  (__to _-off-64-t) (__flags :unsigned-int))
 (cffi:defcfun ("readahead" readahead) ssize-t (__fd :int) (__offset _-off-64-t) (__count size-t))
 (cffi:defcfun ("ctermid" ctermid) :pointer (__s :pointer))
 (cffi:defcfun ("swab" swab) :void (__from :pointer) (__to :pointer) (__n ssize-t))
 (cffi:defcfun ("encrypt" encrypt) :void (__block :pointer) (__edflag :int))
 (cffi:defcfun ("crypt" crypt) :pointer (__key :string) (__salt :string))
 (cffi:defcfun ("fdatasync" fdatasync) :int (__fildes :int))
 (cffi:defcfun ("lockf64" lockf-64) :int (__fd :int) (__cmd :int) (__len _-off-64-t))
 (cffi:defcfun ("lockf" lockf) :int (__fd :int) (__cmd :int) (__len _-off-t))
 (cffi:defcfun ("syscall" syscall) :long (__sysno :long))
 (cffi:defcfun ("sbrk" sbrk) :pointer (__delta intptr-t))
 (cffi:defcfun ("brk" brk) :int (__addr :pointer))
 (cffi:defcfun ("ftruncate64" ftruncate-64) :int (__fd :int) (__length _-off-64-t))
 (cffi:defcfun ("ftruncate" ftruncate) :int (__fd :int) (__length _-off-t))
 (cffi:defcfun ("truncate64" truncate-64) :int (__file :string) (__length _-off-64-t))
 (cffi:defcfun ("truncate" truncate) :int (__file :string) (__length _-off-t))
 (cffi:defcfun ("getdtablesize" getdtablesize) :int)
 (cffi:defcfun ("getpagesize" getpagesize) :int) (cffi:defcfun ("sync" sync) :void)
 (cffi:defcfun ("gethostid" gethostid) :long) (cffi:defcfun ("fsync" fsync) :int (__fd :int))
 (cffi:defcfun ("getpass" getpass) :pointer (__prompt :string))
 (cffi:defcfun ("chroot" chroot) :int (__path :string))
 (cffi:defcfun ("daemon" daemon) :int (__nochdir :int) (__noclose :int))
 (cffi:defcfun ("setusershell" setusershell) :void)
 (cffi:defcfun ("endusershell" endusershell) :void)
 (cffi:defcfun ("getusershell" getusershell) :pointer)
 (cffi:defcfun ("acct" acct) :int (__name :string))
 (cffi:defcfun ("profil" profil) :int (__sample_buffer :pointer) (__size size-t) (__offset size-t)
  (__scale :unsigned-int))
 (cffi:defcfun ("revoke" revoke) :int (__file :string)) (cffi:defcfun ("vhangup" vhangup) :int)
 (cffi:defcfun ("setdomainname" setdomainname) :int (__name :string) (__len size-t))
 (cffi:defcfun ("getdomainname" getdomainname) :int (__name :pointer) (__len size-t))
 (cffi:defcfun ("sethostid" sethostid) :int (__id :long))
 (cffi:defcfun ("sethostname" sethostname) :int (__name :string) (__len size-t))
 (cffi:defcfun ("gethostname" gethostname) :int (__name :pointer) (__len size-t))
 (cffi:defcfun ("setlogin" setlogin) :int (__name :string))
 (cffi:defcfun ("getlogin_r" getlogin-r) :int (__name :pointer) (__name_len size-t))
 (cffi:defcfun ("getlogin" getlogin) :pointer)
 (cffi:defcfun ("tcsetpgrp" tcsetpgrp) :int (__fd :int) (__pgrp_id _-pid-t))
 (cffi:defcfun ("tcgetpgrp" tcgetpgrp) _-pid-t (__fd :int))
 (cffi:defcfun ("rmdir" rmdir) :int (__path :string))
 (cffi:defcfun ("unlinkat" unlinkat) :int (__fd :int) (__name :string) (__flag :int))
 (cffi:defcfun ("unlink" unlink) :int (__name :string))
 (cffi:defcfun ("readlinkat" readlinkat) ssize-t (__fd :int) (__path :string) (__buf :pointer)
  (__len size-t))
 (cffi:defcfun ("symlinkat" symlinkat) :int (__from :string) (__tofd :int) (__to :string))
 (cffi:defcfun ("readlink" readlink) ssize-t (__path :string) (__buf :pointer) (__len size-t))
 (cffi:defcfun ("symlink" symlink) :int (__from :string) (__to :string))
 (cffi:defcfun ("linkat" linkat) :int (__fromfd :int) (__from :string) (__tofd :int) (__to :string)
  (__flags :int))
 (cffi:defcfun ("link" link) :int (__from :string) (__to :string))
 (cffi:defcfun ("ttyslot" ttyslot) :int) (cffi:defcfun ("isatty" isatty) :int (__fd :int))
 (cffi:defcfun ("ttyname_r" ttyname-r) :int (__fd :int) (__buf :pointer) (__buflen size-t))
 (cffi:defcfun ("ttyname" ttyname) :pointer (__fd :int)) (cffi:defcfun ("vfork" vfork) _-pid-t)
 (cffi:defcfun ("fork" fork) _-pid-t)
 (cffi:defcfun ("setresgid" setresgid) :int (__rgid _-gid-t) (__egid _-gid-t) (__sgid _-gid-t))
 (cffi:defcfun ("setresuid" setresuid) :int (__ruid _-uid-t) (__euid _-uid-t) (__suid _-uid-t))
 (cffi:defcfun ("getresgid" getresgid) :int (__rgid :pointer) (__egid :pointer) (__sgid :pointer))
 (cffi:defcfun ("getresuid" getresuid) :int (__ruid :pointer) (__euid :pointer) (__suid :pointer))
 (cffi:defcfun ("setegid" setegid) :int (__gid _-gid-t))
 (cffi:defcfun ("setregid" setregid) :int (__rgid _-gid-t) (__egid _-gid-t))
 (cffi:defcfun ("setgid" setgid) :int (__gid _-gid-t))
 (cffi:defcfun ("seteuid" seteuid) :int (__uid _-uid-t))
 (cffi:defcfun ("setreuid" setreuid) :int (__ruid _-uid-t) (__euid _-uid-t))
 (cffi:defcfun ("setuid" setuid) :int (__uid _-uid-t))
 (cffi:defcfun ("group_member" group-member) :int (__gid _-gid-t))
 (cffi:defcfun ("getgroups" getgroups) :int (__size :int) (__list :pointer))
 (cffi:defcfun ("getegid" getegid) _-gid-t) (cffi:defcfun ("getgid" getgid) _-gid-t)
 (cffi:defcfun ("geteuid" geteuid) _-uid-t) (cffi:defcfun ("getuid" getuid) _-uid-t)
 (cffi:defcfun ("getsid" getsid) _-pid-t (__pid _-pid-t)) (cffi:defcfun ("setsid" setsid) _-pid-t)
 (cffi:defcfun ("setpgrp" setpgrp) :int)
 (cffi:defcfun ("setpgid" setpgid) :int (__pid _-pid-t) (__pgid _-pid-t))
 (cffi:defcfun ("getpgid" getpgid) _-pid-t (__pid _-pid-t))
 (cffi:defcfun ("getpgrp" getpgrp) _-pid-t) (cffi:defcfun ("getppid" getppid) _-pid-t)
 (cffi:defcfun ("getpid" getpid) _-pid-t)
 (cffi:defcfun ("confstr" confstr) size-t (__name :int) (__buf :pointer) (__len size-t))
 (cffi:defcfun ("sysconf" sysconf) :long (__name :int))
 (cffi:defcfun ("fpathconf" fpathconf) :long (__fd :int) (__name :int))
 (cffi:defcfun ("pathconf" pathconf) :long (__path :string) (__name :int))
 (cffi:defcfun ("nice" nice) :int (__inc :int))
 (cffi:defcfun ("execlp" execlp) :int (__file :string) (__arg :string))
 (cffi:defcfun ("execvp" execvp) :int (__file :string) (__argv :pointer))
 (cffi:defcfun ("execl" execl) :int (__path :string) (__arg :string))
 (cffi:defcfun ("execle" execle) :int (__path :string) (__arg :string))
 (cffi:defcfun ("execv" execv) :int (__path :string) (__argv :pointer))
 (cffi:defcfun ("fexecve" fexecve) :int (__fd :int) (__argv :pointer) (__envp :pointer))
 (cffi:defcfun ("execve" execve) :int (__path :string) (__argv :pointer) (__envp :pointer))
 (cffi:defcfun ("dup2" dup-2) :int (__fd :int) (__fd2 :int))
 (cffi:defcfun ("dup" dup) :int (__fd :int))
 (cffi:defcfun ("getwd" getwd) :pointer (__buf :pointer))
 (cffi:defcfun ("get_current_dir_name" get-current-dir-name) :pointer)
 (cffi:defcfun ("getcwd" getcwd) :pointer (__buf :pointer) (__size size-t))
 (cffi:defcfun ("fchdir" fchdir) :int (__fd :int))
 (cffi:defcfun ("chdir" chdir) :int (__path :string))
 (cffi:defcfun ("fchownat" fchownat) :int (__fd :int) (__file :string) (__owner _-uid-t)
  (__group _-gid-t) (__flag :int))
 (cffi:defcfun ("lchown" lchown) :int (__file :string) (__owner _-uid-t) (__group _-gid-t))
 (cffi:defcfun ("fchown" fchown) :int (__fd :int) (__owner _-uid-t) (__group _-gid-t))
 (cffi:defcfun ("chown" chown) :int (__file :string) (__owner _-uid-t) (__group _-gid-t))
 (cffi:defcfun ("pause" pause) :int)
 (cffi:defcfun ("usleep" usleep) :int (__useconds _-useconds-t))
 (cffi:defcfun ("ualarm" ualarm) _-useconds-t (__value _-useconds-t) (__interval _-useconds-t))
 (cffi:defcfun ("sleep" sleep) :unsigned-int (__seconds :unsigned-int))
 (cffi:defcfun ("alarm" alarm) :unsigned-int (__seconds :unsigned-int))
 (cffi:defcfun ("pipe" pipe) :int (__pipedes :pointer))
 (cffi:defcfun ("pwrite64" pwrite-64) ssize-t (__fd :int) (__buf :pointer) (__n size-t)
  (__offset _-off-64-t))
 (cffi:defcfun ("pread64" pread-64) ssize-t (__fd :int) (__buf :pointer) (__nbytes size-t)
  (__offset _-off-64-t))
 (cffi:defcfun ("pwrite" pwrite) ssize-t (__fd :int) (__buf :pointer) (__n size-t)
  (__offset _-off-t))
 (cffi:defcfun ("pread" pread) ssize-t (__fd :int) (__buf :pointer) (__nbytes size-t)
  (__offset _-off-t))
 (cffi:defcfun ("write" write) ssize-t (__fd :int) (__buf :pointer) (__n size-t))
 (cffi:defcfun ("read" read) ssize-t (__fd :int) (__buf :pointer) (__nbytes size-t))
 (cffi:defcfun ("close" close) :int (__fd :int))
 (cffi:defcfun ("lseek64" lseek-64) _-off-64-t (__fd :int) (__offset _-off-64-t) (__whence :int))
 (cffi:defcfun ("lseek" lseek) _-off-t (__fd :int) (__offset _-off-t) (__whence :int))
 (cffi:defcfun ("faccessat" faccessat) :int (__fd :int) (__file :string) (__type :int)
  (__flag :int))
 (cffi:defcfun ("eaccess" eaccess) :int (__name :string) (__type :int))
 (cffi:defcfun ("euidaccess" euidaccess) :int (__name :string) (__type :int))
 (cffi:defcfun ("access" access) :int (__name :string) (__type :int))
 (cffi:defcfun ("_exit" _exit) :void (__status :int)) (cl:defconstant +_unistd-h+ 1)
 (cl:defconstant +_xopen-version+ 500) (cl:defconstant +_xopen-xcu-version+ 4)
 (cl:defconstant +_xopen-xpg-2+ 1) (cl:defconstant +_xopen-xpg-3+ 1)
 (cl:defconstant +_xopen-xpg-4+ 1) (cl:defconstant +_xopen-unix+ 1)
 (cl:defconstant +_xopen-crypt+ 1) (cl:defconstant +_xopen-enh-i-18-n+ 1)
 (cl:defconstant +_xopen-legacy+ 1) (cl:defconstant +stdin-fileno+ 0)
 (cl:defconstant +stdout-fileno+ 1) (cl:defconstant +stderr-fileno+ 2) (cl:defconstant +r-ok+ 4)
 (cl:defconstant +w-ok+ 2) (cl:defconstant +x-ok+ 1) (cl:defconstant +f-ok+ 0)
 (cl:defconstant +seek-set+ 0) (cl:defconstant +seek-cur+ 1) (cl:defconstant +seek-end+ 2)
 (cl:defconstant +f-ulock+ 0) (cl:defconstant +f-lock+ 1) (cl:defconstant +f-tlock+ 2)
 (cl:defconstant +f-test+ 3) (cl:defconstant +_fcntl-h+ 1) (cl:defconstant +o-accmode+ 3)
 (cl:defconstant +o-rdonly+ 0) (cl:defconstant +o-wronly+ 1) (cl:defconstant +o-rdwr+ 2)
 (cl:defconstant +o-creat+ 100) (cl:defconstant +o-excl+ 200) (cl:defconstant +o-noctty+ 400)
 (cl:defconstant +o-trunc+ 1000) (cl:defconstant +o-append+ 2000)
 (cl:defconstant +o-nonblock+ 4000) (cl:defconstant +o-sync+ 10000)
 (cl:defconstant +o-async+ 20000) (cl:defconstant +o-direct+ 40000)
 (cl:defconstant +o-directory+ 200000) (cl:defconstant +o-nofollow+ 400000)
 (cl:defconstant +o-noatime+ 1000000) (cl:defconstant +o-largefile+ 100000)
 (cl:defconstant +f-dupfd+ 0) (cl:defconstant +f-getfd+ 1) (cl:defconstant +f-setfd+ 2)
 (cl:defconstant +f-getfl+ 3) (cl:defconstant +f-setfl+ 4) (cl:defconstant +f-getlk+ 5)
 (cl:defconstant +f-setlk+ 6) (cl:defconstant +f-setlkw+ 7) (cl:defconstant +f-getlk-64+ 12)
 (cl:defconstant +f-setlk-64+ 13) (cl:defconstant +f-setlkw-64+ 14) (cl:defconstant +f-setown+ 8)
 (cl:defconstant +f-getown+ 9) (cl:defconstant +f-setsig+ 10) (cl:defconstant +f-getsig+ 11)
 (cl:defconstant +f-setlease+ 1024) (cl:defconstant +f-getlease+ 1025)
 (cl:defconstant +f-notify+ 1026) (cl:defconstant +fd-cloexec+ 1) (cl:defconstant +f-rdlck+ 0)
 (cl:defconstant +f-wrlck+ 1) (cl:defconstant +f-unlck+ 2) (cl:defconstant +f-exlck+ 4)
 (cl:defconstant +f-shlck+ 8) (cl:defconstant +lock-sh+ 1) (cl:defconstant +lock-ex+ 2)
 (cl:defconstant +lock-nb+ 4) (cl:defconstant +lock-un+ 8) (cl:defconstant +lock-mand+ 32)
 (cl:defconstant +lock-read+ 64) (cl:defconstant +lock-write+ 128) (cl:defconstant +lock-rw+ 192)
 (cl:defconstant +dn-access+ 1) (cl:defconstant +dn-modify+ 2) (cl:defconstant +dn-create+ 4)
 (cl:defconstant +dn-delete+ 8) (cl:defconstant +dn-rename+ 16) (cl:defconstant +dn-attrib+ 32)
 (cl:defconstant +dn-multishot+ 2147483648) (cl:defconstant +posix-fadv-normal+ 0)
 (cl:defconstant +posix-fadv-random+ 1) (cl:defconstant +posix-fadv-sequential+ 2)
 (cl:defconstant +posix-fadv-willneed+ 3) (cl:defconstant +posix-fadv-dontneed+ 4)
 (cl:defconstant +posix-fadv-noreuse+ 5) (cl:defconstant +sync-file-range-wait-before+ 1)
 (cl:defconstant +sync-file-range-write+ 2) (cl:defconstant +sync-file-range-wait-after+ 4)
 (cl:defconstant +splice-f-move+ 1) (cl:defconstant +splice-f-nonblock+ 2)
 (cl:defconstant +splice-f-more+ 4) (cl:defconstant +splice-f-gift+ 8)
 (cl:defconstant +seek-set-1+ 0) (cl:defconstant +seek-cur-1+ 1) (cl:defconstant +seek-end-1+ 2)
 (cl:defconstant +at-fdcwd+ -100) (cl:defconstant +at-symlink-nofollow+ 256)
 (cl:defconstant +at-removedir+ 512) (cl:defconstant +at-symlink-follow+ 1024)
 (cl:defconstant +at-eaccess+ 512))
